name: CI
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14", "16"]

    name: Run tests on Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest"

      - name: Check versions
        run: |
          node --version
          yarn --version
          firefox --version

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test
